name: Deploy Azure Function App

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  AZURE_FUNCTIONAPP_NAME: 'tc-group02-func'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_FUNCTIONAPP_PACKAGE_PATH_DIST: './dist'       
  NODE_VERSION: '18'

permissions:
  id-token: write
  contents: read                     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

     # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
     #- name: 'Login via Azure CLI'
     #uses: azure/login@v1
     #with:
     #  creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        echo Teste
        echo `pwd`
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        echo 'lista de arquivos:'
        echo `ls -l | awk '{print $9}'`
        npm install
        npm run build
        npm run test --if-present
        echo 'lista de arquivos:'
        echo `ls -l dist | awk '{print $9}'`
        popd

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        #package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_DIST }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}